import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo_iwc_by_direct'), Glob('by_direct/*.c') + Glob('*.c'))
env.Program(os.path.join(BIN_DIR, 'demo_iwc_by_win_handle'), Glob('by_win_handle/*.c') + Glob('*.c'))
env.Program(os.path.join(BIN_DIR, 'demo_iwc_by_callback'), Glob('by_callback/*.c') + Glob('*.c'))
env.Program(os.path.join(BIN_DIR, 'demo_iwc_by_model'), Glob('by_model/*.c') + Glob('*.c'))
